### PR TITLE
Added kwargs to some mpl functions

### LINKED ISSUE #193: Pass kwargs to along to matplotlib functions in fatiando.vis.mpl
While using the mpl module I've noticed that I can't put **kwargs as inputs of some functions. For example, if I want to put a transparency in a contourf with pyplot I just add "alpha=alpha_value" and then I got it. But with mpl I cannot do it, so it forces me to go back to pyplot.

I've started thinking to change it, but when I realised that it is a very easy job I wondered: Is there any reason because it wasn't applied in the first time? If there's none, I would be happy to apply those modifications, initially to the functions:
    - contour
    - contourf
    - pcolor
    - points
    - paths
    - square
    - polygon

Greetings!

### PR DESCRIPTION
**Pull request by santis19**
The mpl.py file was modified so now we can use matplotlib kwargs as inputs of the following fatiando.vis.mpl functions:
- contour
- contourf
- pcolor
- points
- paths
- square
- polygon

Fixes #193 

## Checklist:
- [x] Make tests for new code
- [ ] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [x] Include new dependencies in docs, requirements.txt, README, and .travis.yml
- [ ] Documentation builds properly
- [ ] All tests pass
- [ ] Can be merged
- [ ] Changelog entry (leave for last)
- [ ] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last)

### CODE REVIEW

**Comment by leouieda** [comment]
@santis19 this is great, thanks!

Could you use the `kwargs` in one of the cookbook recipes? This is not the proper way to test this but it will have to do until we implement proper testing for the `fatiando.vis` package.

**Comment by santis19** [comment]
Yes, I could! In fact I've tested every edited functions with a simple example. Would you like me to upload an example? Where can I upload it?

**Comment by leouieda** [comment]
@santis19 you can create a new recipe in the `cookbook` folder or modify an existing one to use the kwargs for something.

**Comment by leouieda** [comment]
Hi @santis19, any updates on this?

**Comment by santis19** [comment]
Hi @leouieda!

Sorry, had no time to do the cookbook entry. I'm currently ending my degree thesis and can't find a lot of time write the recipe. But, because writing text during several hours can be exhausting, I will try to find a gap to write the cookbook recipe.

Also, I want to tell you that during my Thesis I was needed to write some codes to process some data as an iterative Moho inversion using the Parker-Oldenburg algorithm taking just the bouguer anomaly as input. Because of the little time I've got and the rush to finish the Thesis I didn't upload it to github nor make a pull request of such codes. Also they are currently not documented (or poorly) and mainly written for my own understanding, I'm afraid. But when I finish it I will be glad to share those codes in order to allow others to make a good use of them.

Greetings!

**Comment by leouieda** [comment]
@santis19 no problem! I just wanted to know the status of this. We're all busy and I didn't mean to rush you.

The Parker-Oldenburg code would be very welcome in Fatiando! Open an issue when you want to start working so that we can discuss the best way forward.

Good luck on your thesis!

**Comment by leouieda** [comment]
I'm closing this Pull Request because it's been inactive for a long time. The branch is probably very out of sync with `master`.

If you want to continue working of this, please [sync your fork](https://help.github.com/articles/syncing-a-fork/), update your branch, and re-submit the PR.  Let me know if you need any help doing this!

Sorry for the hassle! This is not a critique of your work, just a way to keep things fresh in the project. I hope you'll consider re-submitting.

**This is a message template.**

**Pull request closed without merging**
