### PR TITLE
Added gallery plot for radial average power spectrum

### LINKED ISSUE #356: Add gallery plot for radial average power spectrum
We need a gallery plot for the code implemented in #303. Can use the new Hawaii gravity data from #355.

### PR DESCRIPTION
**Pull request by santis19**
Fixes #356 

Added a gallery plot for the radial average power spectrum functions using the Hawaii gravity data from #355.

### Checklist:

- [ ] Make tests for new code (at least 80% coverage)
- [ ] Create/update docstrings
- [ ] Include relevant equations and citations in docstrings
- [ ] Docstrings follow the style conventions
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Include new dependencies in `doc/install.rst`, `environment.yml`, `ci/requirements.txt`.
- [ ] Documentation builds properly (run `cd doc; make` locally)
- [ ] Changelog entry (leave for last to avoid conflicts)
- [ ] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by leouieda** [comment]
@santis19 thanks for doing this!

Could you post the resulting plot here so I can have a look?

**Comment by leouieda** [comment]
Let me know when you're done so I can merge this.

**Comment by santis19** [comment]
This is the resulting plot (generated by 52430618844062abc2cea35c91f0921f37d50ba4):

radial_average_gallery_plot

**Comment by leouieda** [comment]
@santis19 could you include a map of the data next to that plot? This way people will get an idea for what it is when they see the plot in the gallery. Remember that the first thing people see is the plot, not the code.

**Comment by santis19** [comment]
Generated by 21f2c80c7f8811a473ca7f6564d415a772aa7959:

radial_average_gallery_plot

**Comment by leouieda** [comment]
Great! Looks good to me. Let me know when you're done and I'll merge it in.

**Comment by santis19** [comment]
I think it's ready to merge.

**Comment by leouieda** [comment]
Done. Thanks!

**Pull request merged**
