### PR TITLE
Remove error and add a warning for gravmag.transform.upcontinue when height <= 0

### LINKED ISSUE #235: Upward continuation should not give an error when height <= 0
The current behavior of `gravmag.transform.upcontinue` is to use an `assert` to check if the continuation height is > 0. This is OK because you shouldn't downward continue. But I may want to do this in class to show the students what happens when you do. So the `assert` should be a `warnings.warn` instead just to say "Hey, you probably shouldn't do this".

### PR DESCRIPTION
**Pull request by rafaelmds**
Fixes #235

Change the behavior of  `gravmag.transform.upcontinue`. Now, instead of an error its gives a  `warnings.warn` when height <= 0.
This change is mainly for educational purposes (you can test what happen if you calculate for it for height <= 0).

### Checklist:

- [x] Make tests for new code (at least 80% coverage)
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Docstrings follow the style conventions
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `environment.yml`, `ci/requirements-conda.txt` and `ci/requirements-pip.txt`.
- [x] Documentation builds properly (run `cd doc; make` locally)
- [x] Changelog entry (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by leouieda** [comment]
@rafaelmds thanks for the PR! Could you please add the following code to `fatiando/gravmag/tests/test_transform.py`? The function should go below the `test_upcontinue` function and the import at the top. This will test if the warning is being raised properly.

    import pytest


    def test_upcontinue_warning():
        "gravmag.transform upward continuation raises warning if height <= 0"
        model = [Prism(-1000, 1000,-500, 500, 0, 1000, {'density': 1000})]
        shape = (100, 100)
        x, y, z = gridder.regular([-5000, 5000, -5000, 5000], shape, z=-500)
        data = prism.gz(x, y, z, model)
        with pytest.warns(UserWarning):
            up = transform.upcontinue(x, y, data, shape, height=0)
        with pytest.warns(UserWarning):
            up = transform.upcontinue(x, y, data, shape, height=-100)

**Comment by rafaelmds** [comment]
@leouieda Sure! I thought that was necessary but I wasn't sure about it.

**Comment by leouieda** [comment]
No problem. This is the part that always gets newcomers. 

Could you also please change the warning message to "Using 'height' <= 0 means downward continuation, which is known to be unstable." That might be more informative.

**Comment by leouieda** [comment]
@rafaelmds merged! Thanks

**Pull request merged**
