### PR TITLE
Finite-difference wave modeling with an object-oriented API (2nd attempt)

### LINKED ISSUE #70: Make wavefd API Object Oriented
I have very little taste for OOP and generally prefer functions over classes whenever possible. This is how most of the forward modeling modules in Fatiando work (like `fatiando.gravmag.prism`). So this is how I implemented the initial `fatiando.seismic.wavefd`. It has functions that take the velocity model and simulation parameters and produce iterators for the simulation. It works well enough so far.

The problems with this approach:
- requires a lot of function arguments
- verbose to setup
- hard to automate animation in matplotlib in a general way
- **very** difficult to persist a simulation (using pickle) and resume it later (the user needs to know what to pickle and things can get messy)

This last point is what bugs me the most. Long running simulations would benefit from saving checkpoints that can be used to resume at later times or if things crash.

One way to easily resolve most of these issues is to move to an Object Oriented approach. That way, each type of simulation (acoustic, SH, P-SV, 3D-acoustic) would have its own class. The class would be in charge of setting up the simulation parameters (time step, sources, recording stations, saving snapshots to file, etc.) and velocity model (maybe even include conversion to Lamé parameters?). Each class would have the following methods:
- `run`: run the simulation for a given amount of time (starting from the time step)
- `step`: take a single time step
- `animate`: make a plot animating the simulation using matplotlib.animate

There would be no real need for complex class hierarchy because most methods would have to be reimplemented anyway since they are problem specific.

**Update**: I've made a [prototype of these classes](http://nbviewer.ipython.org/github/fatiando/prototypes/blob/master/wavefd-simulation-class.ipynb) on an IPython notebook.  This is the list of things that I'll try to do soon:
- [x] Store the source as pickled string in HDF5
- [x] Use Abstract Base Classes for WaveFD2D
- [x] Fix problem with plots on non-square domains
- [x] Better use of HDF5 attributes to store metadata (should store the Fatiando version string as well)
- [ ] Set sampling rate and don't store all time steps to disk

After these things are done in the prototype, I'll put them in a branch and make a PR.

### PR DESCRIPTION
**Pull request by leouieda**
Fixes #70 

This is a retry at PR #137. I'll start fresh and take the best code and lessons learned from that PR  to make this.

Defines a new API for the `fatiando.seismic.wavefd` module. You now interact with simulation classes instead of generator functions. The simulation data that was thrown away before is now kept in an HDF5 file. This adds the dependency of `h5py` but it's worth it. The class also knows how to produce an animation of the simulation. The video animation can be embedded into the Jupyter notebook.

As an added bonus, replaces the Cython time-stepping functions with numba equivalents without loss 
in speed.
### TODO
- [ ] Option to set the sampling frequency. Would need to keep 2 frames (one before and one after) the desired sample time and do a linear interpolation to get the wavefield at that time. Possible implementation is to see how many iterations are required between each sample and keep the frames around the required number. This won't add to the cost of storage because I'm already keeping 2 frames at a time anyway.
### Checklist:
- [ ] Make tests for new code (at least 80% coverage)
- [ ] Create/update docstrings
- [ ] Include relevant equations and citations in docstrings
- [ ] Docstrings follow the style conventions
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Include new dependencies in `doc/install.rst`, `requirements.txt`, `environment.yml`, `ci/requirements-conda.txt` and `ci/requirements-pip.txt`.
- [ ] Documentation builds properly (run `cd doc; make` locally)
- [ ] Changelog entry (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by leouieda** [comment]
A possible way of not relying on h5py is to optionally use memory-mapped numpy arrays for the cache. It seems that [HDF5 has it's problems](http://cyrille.rossant.net/moving-away-hdf5/) and `numpy.memmap` arrays can be faster (but also larger on disk).

**Comment by eusoubrasileiro** [comment]
uow!!! I'm really going back to this ... esg acoustic, I think I can help on that I have done that for 3D (here)[https://github.com/eusoubrasileiro/fatiando/blob/wavefd_esg_acoustic/fatiando/seismic/wavefd.py]... two weeks more ...

**Comment by leouieda** [comment]
@eusoubrasileiro yep! I'm reusing a lot of your functions from the previous PRs. I have separated things a bit more. The wavelets go into a `seismic/wavelet.py ` module and the FD stuff is in a `seismic/wavefd` package. All public classes are imported into `seismic/__init__.py`. 

Here is an example that I'm using for my geophysics class: http://mybinder.org/repo/leouieda/geofisica2/notebooks/notebooks/1-ondas-sismicas.ipynb

I'm hopping to get this finished in October when I'll have some time off from work.

**Comment by eusoubrasileiro** [comment]
interesting about the hdf5 problems... some of the suggestions on your link is to use numpy format *.npy I will try to take a deeper look in this soon.

**Review by eusoubrasileiro — COMMENTED** [review]
new ipython API?! nice!

**Pull request closed without merging**
