### PR TITLE
Modified carvetopo to mask mesh below a surface

### PR DESCRIPTION
**Pull request by cmeessen**
Tackles #312

In order to restrict the growth of the harvester I slightly modified `carvetopo()` (after suggestions by @leouieda). The new parameter _below_ reverses the masking process.

The image below shows a prism mesh that has been successfully masked above and below two surfaces.

snapshot

I am not familiar with testing the code. Just by looking at the results the carving seems to be working fine. Would an automated test be required?
### Checklist:
- [x] Make tests for new code (at least 80% coverage)
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Docstrings follow the style conventions
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `requirements.txt`, `environment.yml`, `ci/requirements-conda.txt` and `ci/requirements-pip.txt`.
- [x] Documentation builds properly (run `cd doc; make` locally)
- [x] Changelog entry (leave for last to avoid conflicts)
- [x] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by leouieda** [comment]
@cmeessen thanks for taking the time to do this! I'll review the code as soon as I have some time.

We had a very loose policy on tests but I've come to regret it. Having a solid test suite makes things like porting to Python 3 so much easier. So our new policy (enforced by Github) is that some form of tests are required. But don't worry, I can walk you through writing some tests for this code as well. 

Usually we test the output against simple inputs for which we know the correct answer (like a flat topography on a regular grid in your case). Other useful things to test are corner cases (for example using topography that has a mask). 

Refer to the development version of our docs for some information of how to get started: www.fatiando.org/dev/develop.html  (notice the `/dev/` in the url).

Your tests will need to go here: https://github.com/fatiando/fatiando/blob/master/fatiando/tests/mesher/test_prism_mesh.py

These are some good examples of tests in #297 : https://github.com/fatiando/fatiando/tree/gridder-package/fatiando/gridder/tests

It would be awesome if you also added a sample plot to the new [gallery](http://www.fatiando.org/dev/gallery/index.html). Here is a [sample gallery plot](https://github.com/fatiando/fatiando/blob/master/gallery/3-mesh/prism_mesh.py). It becomes [this](http://www.fatiando.org/dev/gallery/3-mesh/prism_mesh.html#sphx-glr-gallery-3-mesh-prism-mesh-py) when the docs are built.

**Comment by leouieda** [comment]
Also, make sure that you configured git with the same email address that you use for your github.com account. Otherwise Github won't recognize that the commit came from you.

**Comment by cmeessen** [comment]
Thank you for the explanations, I also corrected the email addresses. A small script for the gallery will follow soon, as well as hopefully a test script.

**Comment by cmeessen** [comment]
I finally had some time to create a test for carvetopo. The code tests whether a 2x1x1 PrismMesh is being cut above or below a flat plane. Therefore, a set of reference PrismMeshes is generated which are then being compared to the carved PrismMeshes. I found it particularly difficult to test the prisms for similarity, which is why the code now seems a bit cumbersome to me. Please let me know if you have suggestions for improvements.

**Comment by leouieda** [comment]
@cmeessen I agree that testing prisms is way more cumbersome than it should be. 

This PR is great and is ready to be merged. All that's left is making an entry in `doc/changelog.rst`. If #314 is merged first, pull in the changes from `master` before editing the changelog to avoid conflicts. But it's not a big deal if you end up with a conflict. It happens all the time.

**Comment by cmeessen** [comment]
@leouieda this PR is ready to merge now as well. I still would like to create a gallery plot but since I have problems with mayavi (QDate has already been set to version 1) I would rather like to wait until there is a proper replacement for this package.

**Comment by leouieda** [comment]
@cmeessen merged. Thanks!

Yes, don't worry about the gallery plots for now. Mayavi is a mess and we're working on a replacement using just matplotlib. It won't look as good but maintenance will be much easier.

**Pull request merged**
