### PR TITLE
Documenting and testing wavefd-simulation-class #137

### PR DESCRIPTION
**Pull request by eusoubrasileiro**
I don't want to be hard with python but it seams its documentation features for abstract/interfaces/derived class or methods lack functionality.  For documenting methods that are going to be used by derived classes I am now copying on all classes with equal methods. Python doesn't check if your method is not complying with the mother method it s overriding. 

I wrote few test cases after watching the software carpentry lessons.

I will push more stuff as they come. It takes time a long time to understand someone-else's code without or with very few comments!!! @leouieda luckily I am learning some things.

Copying from yours [137](https://github.com/fatiando/fatiando/pull/137) 
I need to reference [this](http://nbviewer.ipython.org/github/fatiando/tutorials/blob/master/Simulating_seismic_waves.ipynb) most recent ipython notebook usage procedures and the [old one](http://nbviewer.ipython.org/github/fatiando/prototypes/blob/master/wavefd-simulation-class.ipynb)

- [x] Make tests for new code  (*I've done some ... working one more and maybe some doctests*)
- [x] Create/update doc-strings (*working on ... very very tough not being my code!* )
- [x] Update requirements (*I think it's okay now*)
- [x] Code follows PEP8 style conventions (*working on ..*)
- [x] Code and docs have been spell-checked (*for the end...*)
- [x] Changelog entry
- [x] Documentation builds properly (*builds properly but need more...*)
- [x] All tests pass (*so far passed ... working on more!*)
- [ ] Can be merged 

Progress updates:
Updated (20/01/2015):
Porting my scalar code and cookbook.
Soon I will try to refactor all old cookbook code to get rid of everything old.
Need to do:
- [x] Re-factor scalar + dumping region 
- [x] Re-factor scalar cookbook (do not re-factor the others) implicit optimizing plotting and animation code.
- [x] add padding support again needed for dumping region (I'll leave it for future for sh and psv)
- [x] Fix doc strings (don't forget development [guide](http://fatiando.readthedocs.org/en/latest/develop.html))
- [ ] Tests coverage acceptance
- [ ] Update installation requirements : h5py; all IPython notebook dependencies (pip recommended for latest);  `animate` requires libavcodec-extra-54 and libav-tools (In Ubuntu 14.04 LTS)

About documenting classes:

* Base class abstract methods should not have docstrings.

### CODE REVIEW

**Comment by eusoubrasileiro** [comment]
@leouieda after a lot of work to understand your code I still could not understand everything.  hahaha still missing documentation.

Ive written some more tests. 
My old `Scalar` class is totally documented. 
Sources are fully documented.

Well I have I fixed at least (I guess) most of the docstrings.
But I haven't finished reviewing the documentation for the other classes.
I haven't fixed the cookbooks or get rid of all old code. 

**Your help needed**

What I need from you is to take I look on the way I am going with the docs. I haven't finished but...
I suggest that the common methods of the simulation classes should be on `wavefd` docstring in two topics: *Simulation Storage Access* and *Simulation (rich) display*. 
Doing so we would not document the methods on those topics on the body of the classes, leaving the classes cleaner. My worry is that the module `wavefd` is getting really huge.

**Comment by leouieda** [comment]
@eusoubrasileiro thank you so much for helping with this! The semester is finally over at the university so I might have a chance to look at this next week.

**Comment by eusoubrasileiro** [comment]
although I've installed numba when I run `make test` I am getting the following error:

```
======================================================================
ERROR: gravmag.tesseroid numba and pure python implementations give same result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/andre/PycharmProjects/fatiando/test/test_gravmag_tesseroid.py", line 89, in test_numba_vs_python
    nb = func(lon, lat, height, model, engine='numba')
  File "/home/andre/PycharmProjects/fatiando/fatiando/gravmag/tesseroid.py", line 383, in potential
    ratio=ratio, engine=engine, njobs=njobs, pool=pool)
  File "/home/andre/PycharmProjects/fatiando/fatiando/gravmag/tesseroid.py", line 277, in _dispatcher
    field])
  File "/home/andre/PycharmProjects/fatiando/fatiando/gravmag/tesseroid.py", line 301, in _forward_model
    module = _get_engine(engine)
  File "/home/andre/PycharmProjects/fatiando/fatiando/gravmag/tesseroid.py", line 224, in _get_engine
    module = _tesseroid_numba
NameError: global name '_tesseroid_numba' is not defined

----------------------------------------------------------------------
Ran 174 tests in 3504.121s

FAILED (errors=1)
make: *** [test] Error 1
```

am I missing something...?

**Comment by leouieda** [comment]
Are you sure that you can import numba?

**Comment by eusoubrasileiro** [comment]
no I am not sure! ... I am fighting to install numba on ubuntu...

**Comment by eusoubrasileiro** [comment]
@leouieda  now numba working. Though I don't know what has broke AppVeyor.

About the docs, although I like the new style I miss something. 
Since, for example, `wavefd.py` has too many classes you get lost when you come to the documentation and search for a specific class. I took a look in the Sphinx documentation but I will try more, something like a summary would be very handy. 

Despite of that IPython widgets is something really nice but according to `doctest` it is subject to changes in future, just to let you know. 

When you have a time take a look on what I wrote above, I still need help on documenting it. Above all else this simulation classes are really amazing in this new format!

**Comment by leouieda** [comment]
Wow, why are there so many different commits in this branch? Things probably got a bit messed up with all the recent PRs. I'm running a merge on your branch here to try to make things a bit cleaner and resolve all the merge conflicts (there are many).

I've made a PR from the branch I've used to resolve the conflicts on to yours. You can merge it to make things up-to-date with master.

**Comment by leouieda** [comment]
OK, I don't like how we are doing this with so many different branches. This is creating a lot of headaches!

We should probably just both commit to the same branch. What do you think? Would you be comfortable pushing things to the main repo? Just need to be extra careful not to mess up `master`. We would also need to coordinate our development so that we don't break each others code (we'd need to talk more, which is not a bad things :facepunch:).

**Comment by leouieda** [comment]
OK, once you merge the PR with the conflict resolutions the diffs should be more sane. I've had a look at the code and I think we can merge this and do some more later. There is still a lot of repeated code and I agree that the module is way too big. We can safely delete the old code because no one would use it once the classes are done, so that removes some of the volume.

**Comment by leouieda** [comment]
Well, that was quick. Don't you have a job?

**Comment by leouieda** [comment]
We should probably focus first in simplifying the code. We can make the proper documentation after the code is settled then. What do you think?

**Comment by eusoubrasileiro** [comment]
haah I do have I job but I just entered on github to see what was going on. Just coincidence heh lucklily

**Comment by eusoubrasileiro** [comment]
calling you

**Pull request closed without merging**
