### PR TITLE
Implement upward continuation and reduction to the pole in the frequency domain

### PR DESCRIPTION
**Pull request by leouieda**
This PR adds two things to `fatiando.gravmag.transform`: 
* Option to `upcontinue` for upward continuation using the FFT
* Function `reduce_to_pole` for pole reduction of magnetic data using FFT

## Checklist:

- [x] Make tests for new code
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in docs, requirements.txt, README
- [x] Documentation builds properly
- [x] All tests pass
- [x] Can be merged
- [x] Changelog entry

### CODE REVIEW

**Comment by leouieda** [comment]
Waiting for #196 to get the extra tests and fix to gridder.

**Comment by leouieda** [comment]
The space domain approach doesn't work very well (doesn't pass the tests) and is quite slow to run. I'm thinking of getting rid of it in favour of FFT. Padding did great for edge effects.

**Comment by leouieda** [comment]
Testing `upcontinue` almost done:
- [ ] Make test for `upcontinue` using magnetic data.

**Comment by eusoubrasileiro** [comment]
nice!! really nice!!

**Comment by leouieda** [comment]
:+1:

**Pull request merged**
