### PR TITLE
Adding duecredit decorators to all relevant functions

### LINKED ISSUE #292: Provide citation information for all functions/classes/modules
We need to make a better job of providing citation information for Fatiando components. The coolest thing I've seen so far is [duecredit](https://github.com/duecredit/duecredit/). We can annotate our code with references and the user can use duecredit to generate a full list of references (including external libraries).

### PR DESCRIPTION
**Pull request by mtb-za**
Fixes #292 

Starting to go through everything to give it a citation.

### Checklist:

- [ ] Make tests for new code (at least 80% coverage)
- [ ] Create/update docstrings
- [ ] Include relevant equations and citations in docstrings
- [ ] Docstrings follow the style conventions
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Include new dependencies in `doc/install.rst`, `environment.yml`, `ci/requirements.txt`.
- [ ] Documentation builds properly (run `cd doc; make` locally)
- [ ] Changelog entry (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by mtb-za** [comment]
Is there a reason that the citations in `gravmag.imaging` are only in the main docstring, not in the ones for individual methods? Should I add them there as I go through?

**Comment by mtb-za** [comment]
## Modules with credit
I will add these as I go, so this will be edited.
- [ ] gravmag
    - [x] gravmag.eqlayer
    - [x] gravmag.imaging
    - [x] gravmag.magdir (done in #222 and #293)
    - [x] gravmag.normal_gravity
    - [x] gravmag.polyprism
    - [x] gravmag.prism
    - [x] gravmag.sphere
    - [x] gravmag.talwani
    - [x] gravmag.tensor
    - [x] gravmag.tesseroid
    - [x] gravmag.transform

**Comment by leouieda** [comment]
@mtb-za thanks for going through the trouble of adding these!

> Is there a reason that the citations in some places are only in the main docstring, not in the ones for individual methods?

Yes. Inconsistent practices on my part and old code that hasn't been updated in years :)
I really need to aggressively remove old and broken stuff from Fatiando.

**Comment by leouieda** [comment]
> Should I add them to function docstrings as I go through them all?

That would be great!!

**Pull request closed without merging**
