### PR TITLE
An Object Oriented interface for seismic wave finite-differences simulations

### LINKED ISSUE #70: Make wavefd API Object Oriented
I have very little taste for OOP and generally prefer functions over classes whenever possible. This is how most of the forward modeling modules in Fatiando work (like `fatiando.gravmag.prism`). So this is how I implemented the initial `fatiando.seismic.wavefd`. It has functions that take the velocity model and simulation parameters and produce iterators for the simulation. It works well enough so far.

The problems with this approach:
- requires a lot of function arguments
- verbose to setup
- hard to automate animation in matplotlib in a general way
- **very** difficult to persist a simulation (using pickle) and resume it later (the user needs to know what to pickle and things can get messy)

This last point is what bugs me the most. Long running simulations would benefit from saving checkpoints that can be used to resume at later times or if things crash.

One way to easily resolve most of these issues is to move to an Object Oriented approach. That way, each type of simulation (acoustic, SH, P-SV, 3D-acoustic) would have its own class. The class would be in charge of setting up the simulation parameters (time step, sources, recording stations, saving snapshots to file, etc.) and velocity model (maybe even include conversion to Lamé parameters?). Each class would have the following methods:
- `run`: run the simulation for a given amount of time (starting from the time step)
- `step`: take a single time step
- `animate`: make a plot animating the simulation using matplotlib.animate

There would be no real need for complex class hierarchy because most methods would have to be reimplemented anyway since they are problem specific.

**Update**: I've made a [prototype of these classes](http://nbviewer.ipython.org/github/fatiando/prototypes/blob/master/wavefd-simulation-class.ipynb) on an IPython notebook.  This is the list of things that I'll try to do soon:
- [x] Store the source as pickled string in HDF5
- [x] Use Abstract Base Classes for WaveFD2D
- [x] Fix problem with plots on non-square domains
- [x] Better use of HDF5 attributes to store metadata (should store the Fatiando version string as well)
- [ ] Set sampling rate and don't store all time steps to disk

After these things are done in the prototype, I'll put them in a branch and make a PR.

### PR DESCRIPTION
**Pull request by leouieda**
Implement "simulator" objects to run the finite-differences time steppers. Re-uses the Cython time-steps and wraps them in classes, instead of the old generator functions (using `yield` statements).

Based on [this prototype](http://nbviewer.ipython.org/github/fatiando/prototypes/blob/master/wavefd-simulation-class.ipynb).

Fixes #70 

## Storage

The simulation classes store each time frame in an [HDF5](http://www.h5py.org/) file. When you need the simulation results, the class digs into the cache file and returns the data requested. Animation methods load the snapshots from the file and make animations using matplotlib.animate. 

The cache file stores all data needed to resume a simulation later. The `from_cache` method rebuilds a simulation object from the cache file and computations can be resumed  right away, Source functions are also stored in the cache file as pickles.

## Rich display

Simulation and source wavelet classes have rich display capabilities for use with IPython notebooks. The `snapshot` method loads a time step from the cache file and plots it. The `_repr_png_` for the simulations is the last time step. There is an option to convert the animation to a video and embed it in the IPython notebook.

## Sample usage

A sample notebook using the code from this  PR is on the [tutorials repo](http://nbviewer.ipython.org/github/fatiando/tutorials/tree/master/). It will be updated along with the PR.

## Testing

- [ ] We need an analytic solution against which we can test the simulation results. 
- [ ] I would also like to have Python+numpy versions of the time stepping function so that we can test them against each other (and also use as a benchmark). It wouldn't hurt having a numba implementation as well.

## TODO

- [ ] Allow the user to  specify the boundary conditions. Right now they are fixed as free-surface on top and absorbing on the other sides. (**Can/should be left for a future PR**)
- [ ] Get rid of redundancy in plotting functions. There is a lot of repeated code.
- [ ] Clean-up the way things are stored in the cache file. My use of HDF5 is far from ideal.
- [ ] Try to adapt the elastic P-SV time step so that I don't have to copy (and make C-contiguous) the arrays when initializing the simulation (in the beginning of `run`).  (**Can/should be left for a future PR**)
- [ ] Figure out what to do with old code. Should we delete it or only deprecate it (and stop  using it in the cookbook). I think deleting wouldn't be too bad  since not many people use it anyway. Plus, the simulation classes are just so much better.

## Checklist

- [ ] Make tests for new code
- [ ] Create/update docstrings
- [ ] Update requirements
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Changelog entry
- [ ] Documentation builds properly
- [ ] All tests pass
- [ ] Can be merged

### CODE REVIEW

**Comment by leouieda** [comment]
@eusoubrasileiro I've been thinking of replacing the hacked version of movie embedding that I made with [moviepy](https://github.com/Zulko/moviepy). I'll move some of the functions that are independent of the simulation to a `utils` module in `fatiando.vis`. I'm still investigating but just to let you know.

**Comment by eusoubrasileiro** [comment]
@leouieda ok sire. That code is a little confusing I could not document it properly. BTW take a look on my PR when you've a time too.

**Comment by leouieda** [comment]
It might be worth checking this out for the ASCII progress bar https://github.com/ContinuumIO/dask/pull/485

**Comment by eusoubrasileiro** [comment]
I don't want to be hard with python but it seams its documentation features for abstract/interfaces/derived class or methods lack functionality.  For documenting methods that are going to be used by derived classes I am now copying on all classes with equal methods. Python doesn't check if your method is not complying with the mother method it s overriding. 

I wrote few test cases after watching the software carpentry lessons.

I will push more stuff as they come. It takes time a long time to understand someone-else's code without or with very few comments!!! @leouieda luckily I am learning some things.

Copying from yours [137](https://github.com/fatiando/fatiando/pull/137) 
I need to reference [this](http://nbviewer.ipython.org/github/fatiando/tutorials/blob/master/Simulating_seismic_waves.ipynb) most recent ipython notebook usage procedures and the [old one](http://nbviewer.ipython.org/github/fatiando/prototypes/blob/master/wavefd-simulation-class.ipynb)

- [x] Make tests for new code  (*I've done some ... working one more and maybe some doctests*)
- [x] Create/update doc-strings (*working on ... very very tough not being my code!* )
- [x] Update requirements (*I think it's okay now*)
- [x] Code follows PEP8 style conventions (*working on ..*)
- [x] Code and docs have been spell-checked (*for the end...*)
- [x] Changelog entry
- [x] Documentation builds properly (*builds properly but need more...*)
- [x] All tests pass (*so far passed ... working on more!*)
- [ ] Can be merged 

Progress updates:
Updated (20/01/2015):
Porting my scalar code and cookbook.
Soon I will try to refactor all old cookbook code to get rid of everything old.
Need to do:
- [x] Re-factor scalar + dumping region 
- [x] Re-factor scalar cookbook (do not re-factor the others) implicit optimizing plotting and animation code.
- [x] add padding support again needed for dumping region (I'll leave it for future for sh and psv)
- [x] Fix doc strings (don't forget development [guide](http://fatiando.readthedocs.org/en/latest/develop.html))
- [ ] Tests coverage acceptance
- [ ] Update installation requirements : h5py; all IPython notebook dependencies (pip recommended for latest);  `animate` requires libavcodec-extra-54 and libav-tools (In Ubuntu 14.04 LTS)

About documenting classes:

* Base class abstract methods should not have docstrings.

**Comment by eusoubrasileiro** [comment]
@leouieda after a lot of work to understand your code I still could not understand everything.  hahaha still missing documentation.

Ive written some more tests. 
My old `Scalar` class is totally documented. 
Sources are fully documented.

Well I have fixed at least (I guess) most of the docstrings.
But I haven't finished reviewing the documentation for the other classes.
I haven't fixed the cookbooks or get rid of all old code. 

**Your help needed**

What I need from you is to take I look on the way I am going with the docs. I haven't finished but...
I suggest that the common methods of the simulation classes should be on `wavefd` docstring in two topics: *Simulation Storage Access* and *Simulation (rich) display*. 
Doing so we would not document the methods on those topics on the body of the classes, leaving the classes cleaner. My worry is that the module `wavefd` is getting really huge and so its docs.

**Comment by leouieda** [comment]
@eusoubrasileiro I know, this code is very badly documented and a terrible hack. We should talk about this code and make a plan of action before anything.

**Comment by eusoubrasileiro** [comment]
Wow you are fast. Have done anything wrong? hehe I thought I was suppose to bring back things here instead of using my old branch. It's up to you master.

**Comment by eusoubrasileiro** [comment]
The "terrible hack" expression is new to me hehe Ok I will stop here and wait some time so we can talk about it. In any case I can revert this commit if you want

**Comment by leouieda** [comment]
I don't even remember a lot of this code. You shouldn't worry too much about the docstring of the base classes. They are mostly not for users and so it's not a problem if they aren't on the website. They **shouldn't** be on the website.

I'm more worried about cleaning up the code and not breaking the functionality. This is why we need tests first. The tests should run some simple scenarios and a notebook could be a more complete test of the rich display part. That way we can change the code without worrying that we break something.

**Comment by leouieda** [comment]
No, don't need to revert. See if you can figure out the code but it would be easier to talk (can be skype, but not this weekend).

**Comment by leouieda** [comment]
Try to see if you can get some tests and a notebook running (like the one in the tutorials repo). You can bring the notebook over to this repository in a `tutorials` folder in the root directory.

**Comment by eusoubrasileiro** [comment]
Some new todo list:

- [ ] fix old cookbook recipes that are broken (e. g. cookbook/seismic_wavefd_scalar.py)

**Comment by eusoubrasileiro** [comment]
#### Some thoughts on simulation classes refactoring (class design) ####

I see that all simulation classes have 3 categories of functionalities

1. Simulation math (variables and algorithm code for the specific partial differential equation)

    e. g. methods `__init__()`, `add_point_source`, `add_any_source`, `_time_step`
    e. g. variables `dx`, `dz`, `dt`, `it`, `density`, `shape`, `velocity`, `Mx`, `Mz`, `mu`, `svel`, `pvel`, `sources` etc.

2. HDF5 simulation recording (simulation serialization, persistence) and access 

    e. g. methods `create_tmp_cache`, `get_cache`, `init_panels`, `init_cache`, `cache_panels`, `expand_cache`, `__getitem__`, `run`(it is totally done inside a hdf5 file) 
     e. g. variables `*h5py.File`, hdf5 data sets, hdf5 attributes etc.

3. Plotting, visualization and understanding results (including ipython notebook features) 

    e. g. methods `_repr_png_`, `explore`, `snapshot`, `animate`
    e. g. variables ... you got the idea

I am thinking that developing following this hierarchy top 1 to 3 bottom would be much easier and also logical.  Having a class full of methods and variables is not easy to maintain, understand or expand.

One initial step we are taking is to move visualization stuff to `fatiando.vis`. We could link our class methods to functions there and avoid duplicates making it more reusable.

*Some other brain storm thoughts:*
We could design every simulation class based on 3 classes. First simulation algorithm, having a subclass? of arguments package. Second simulation hdf5 persistence (derived from the first) using the arguments package to more easily write data data sets and attributes. Third visualization stuff (derived from the second). ?

Or use python 3, multiple inheritance ? 
`Simulation(Algorithm, Hdf5Simulation)` and write just the visualization part... ? 

well those have been my thoughts until now...

**Comment by leouieda** [comment]
@eusoubrasileiro thanks so much for putting work into this! I haven't been able to give you the proper attention, sorry :hankey: 

You mentioned you're having trouble with the branch and Travis CI. This PR is getting very confusing quite fast. Don't worry too much right now but we should consider starting a new branch for this before merging. We can just copy/paste the code from here to the new branch. That would make the history cleaner and eliminate all the merges from master that are causing all this trouble. But we can leave that for later.

Once I submit my thesis we should get together and discuss your design ideas!

**Comment by eusoubrasileiro** [comment]
@leouieda don't worry man! just need to know you are alive heheh you are! hahah

Good work there! Focus on your thesis! cya later!

**Comment by eusoubrasileiro** [comment]
http://pysit.readthedocs.org/en/release/0.5/examples/animation.html to take a look

**Comment by leouieda** [comment]
I remember seeing that a long time ago when first building this in Fatiando. I don't really like the API for that code. It seems very Fortranish. But we should have a better look at their source code. Maybe there is something in there to salvage. The project appears to be dead now, the last update was in 2013.

**Comment by leouieda** [comment]
I've been thinking about the volume of code here and I finally agree with you that this should be in separate files (sorry for taking so long to see it). I think the best way would be to make `wavefd` a package inside `seismic` with files to  separate things neatly. But the user wouldn't need to see this. We can import the public facing classes in  `wavefd/__init__.py` and the user can still do `from fatiando.seismic.wavefd import ElasticSH` for example.

However, this PR is already out of hand. I'll have to take a look at this in March because I'll be using it in my classes again. Hopefully we can organize things and finish this off then. 

Thanks again for all the help with this!

**Comment by eusoubrasileiro** [comment]
holaa

yes I think that project is dead as well...  good to know you knew about it beforehand
I will look at it with the same spirit sometime...

hehehe about the wavefd package. No problema man! there we go! 
GOOD! I like the idea! Exactly what I think we need! 

we are growing and improving the package that's what matters! :+1:

**Comment by leouieda** [comment]
I'm closing this Pull Request because it's been inactive for a long time. The branch is probably very out of sync with `master`.

If you want to continue working of this, please [sync your fork](https://help.github.com/articles/syncing-a-fork/), update your branch, and re-submit the PR.  Let me know if you need any help doing this!

Sorry for the hassle! This is not a critique of your work, just a way to keep things fresh in the project. I hope you'll consider re-submitting.

**This is a message template.**

**Pull request closed without merging**
