### PR TITLE
Setup minimal gallery for Fatiando

### PR DESCRIPTION
**Pull request by leouieda**
Uses [sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery) to setup a minimal gallery (like the [maptlotlib gallery](http://matplotlib.org/gallery.html)). The idea is to create the basis for the gallery and fill it up with plots in other PRs (ideally with the help of other devs).

Continues the work started in #266.

I posted a temporary example to [fatiando.org/tmp-docs](http://www.fatiando.org/tmp-docs/gallery/index.html) so others can have a look.

### Checklist:

- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `requirements.txt`, `environment.yml`, and `README.rst`
- [x] Documentation builds properly (run `make docs` locally)
- [x] Changelog entry (leave for last)
- [x] Building and pushing from TravisCI works
- [x] Include links to the gallery in the documentation (front-page, docs page, install)
- [x] At least one example for gridder, mesher, vis, gravmag and seismic

Notification for @fatiando/core-devs

### CODE REVIEW

**Comment by leouieda** [comment]
Finally got Mayavi plots to work in the gallery: http://www.fatiando.org/tmp-docs/gallery/meshes_grids/prism_model.html

This will open the way for a model collection gallery in the future.

**Comment by eusoubrasileiro** [comment]
Uow this is getting prettier and prettier!! just fixed your broken link, dont get upset hehe

**Comment by leouieda** [comment]
@eusoubrasileiro oops. That's what I get for having 20 tabs open. Thanks! 

I just need to test if the docs build properly on TravisCI now. I'll leave the gallery with only one example from each package as a guide for future work. We can fill it up on subsequent PRs so it's not concentrated work. New PRs can already add their scripts here instead of the cookbook.

**Comment by leouieda** [comment]
OK, this is done. There are only 1-2 examples per package right now. We'll need to add more later but this gets us the infrastructure needed.

**Pull request merged**
