### PR TITLE
Re-organize documentation and website

### LINKED ISSUE #216: Use autosummary in the docs
The sphinx [autosummary](http://sphinx-doc.org/latest/ext/autosummary.html) plugin is a nice way to get a list of classes, methods, functions, etc. We should use it in the docs instead of listing out the members of a module with bullet points (`* :class:...`).

For example, the class and function list can be replaced by:

    .. autosummary::
        MyClass
        my_func

Each class can also list their most important methods the same way. In the class docstrings, use:

    Main methods and attributes:
    .. autosummary::
        MyClass.method1

### PR DESCRIPTION
**Pull request by leouieda**
Fixes #216 #248 #11

Attempt  to reorganize the documentation into a more useful form, specially for new users.  The current site has 2 main section of documentation: the API reference and the cookbook. The reference is built from text taken the module and package docstrings. The modules pages also list all functions and classes with their associated docstrings.  The cookbook is a collection of .`.py` files. There is no text explaining things and the output of the scripts is not shown.

I think the docs are missing:

* Narrative documentation: text explaining where things are and how they work along with the source code examples.
* Figures: there is practically no code accompanied by the figures of results produced.
* Simple API reference: the specification of functions and classes is mixed with a lot of text. Sometimes you need to go through 3-4 pages to find the docs for a particular function. A better reference would list all functions and classes with links to their documentation (taken from the docstrings).

Both of these would make the package more friendly and attractive to new users.

Main changes:

* Removed the old "Library Reference" section. It was replaced by an API reference (as specified above) and a User Guide (narrative documentation)
* The API Reference lists all functions/classes from all modules and packages.  The page gets a bit big but it's very convenient to have it all in a single page. You can search with `Ctrl+f`. The modules of subpackages (gravmag, inversion, etc) are listed for now.
* Pages for each function and class are automatically generated by `autosummary`
* The User Guide is built from Jupyter notebooks in `doc/userguide`. This is better because we can include Mayavi figures and the user can download and run the code.
* The User Guide has a page for each module/package. The idea is to have a description of what the module/package does and simple examples of every function/class in it. The examples should be simple and are meant to show what Fatiando can do. More complicated examples would be left for a Tutorial section.
* The doc build runs the notebooks and converts to `rst`. This guarantees that the results are updated always. We could even plug in some doctesting here in the future.
* I put a lateral navigation bar in most pages to help with navigation.
* The Overview in the front page links to the User Guide sections.
* The Guide and API link to each other.

I put a preview of the site on http://www.fatiando.org/tmp-docs/

### Checklist:

- [ ] Make tests for new code (at least 80% coverage)
- [ ] Create/update docstrings
- [ ] Include relevant equations and citations in docstrings
- [ ] Docstrings follow the style conventions
- [ ] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Include new dependencies in `doc/install.rst`, `requirements.txt`, and
  `README.rst`
- [ ] Documentation builds properly (run `make docs` locally)
- [ ] Changelog entry (leave for last)

### CODE REVIEW

**Comment by leouieda** [comment]
@mtb-za @birocoles @eusoubrasileiro @drandykass I would love some feedback on this.

**Comment by mtb-za** [comment]
I think that this is a really great idea.

Will see what I can come up with for narrative script examples.

**Comment by leouieda** [comment]
@mtb-za thank you for the feedback. I'll start writing the user guide as soon as I get a change. I'll ask for feedback again when I have a draft.

Of course, any ideas/wants are welcome!

**Comment by leouieda** [comment]
I'm going to split this into separate PRs for each change. This is too big and I'll end up never completing it this way. I'll post the PRs here when I open them.

**Comment by leouieda** [comment]
https://github.com/spatialaudio/nbsphinx is probably the best way to use the notebooks for the userguide.

**Comment by mtb-za** [comment]
Love the new gallery.

**Comment by eusoubrasileiro** [comment]
ta fodástico! :+1:

**Comment by leouieda** [comment]
@mtb-za @eusoubrasileiro thanks! This is the latest version http://www.fatiando.org/dev/gallery/index.html

**Comment by leouieda** [comment]
Closing this in favor of incremental changes that have been made in other PRs.

**Pull request closed without merging**
