### PR TITLE
Build docs in TravisCI and host on the fatiando.github.io repo

### LINKED ISSUE #131: Self host the docs and build them on TravisCI
The problem with ReadTheDocs  is getting all the dependencies installed. For example, I can't include the plots in the cookbook using the matplotlib `plot_directive` extension because I have to mock matplotlib for RTD.

The solution would be to host the docs on a `gh-pages` branch of a repo on the Fatiando Organization. The docs could be build on TravisCI as part of the test suite for  the `fatiando` repo and pushed to that repo is the commit is pushed to `master` (i.e., the PR is merged). This would also make sure that PRs don't break the docs.

Once fatiando.org points to the `fatiando.github.io` repo, the docs could be served on `fatiando.org/docs` if the docs repo is `docs`. Upon releases, we could fork this repo to `docs-v1.3` to  keep the history. This way, `docs` would always be the latest docs.

### PR DESCRIPTION
**Pull request by leouieda**
Moving away from ReadTheDocs has it's benefits, like being able to install things (no need to mock the imported modules). 

The docs are built using TravisCI and pushed to the `gh-pages` branch of [fatiando/docs](https://github.com/fatiando/docs) when the Travis build is trigger from the `master` branch (i.e., the commit was directly to `master` or the PR has been merged).

Building the docs and checking the links is part of the test suite now.

Fixes #131 

**Update 5 March 2015**: The docs are now the official website. This PR will make the push to fatiando.github.io. Doc builds for previous versions are stored in repositories called v0.1, v0.2, etc and served from fatiando.github.io/v0.1, etc.

### CODE REVIEW

**Comment by leouieda** [comment]
Waiting for fatiando.org to point to the gh-pages build (fatiando.github.io). Once that is done, this can be merged.

**Comment by leouieda** [comment]
Recent idea that I'd like to have before merging this as well.

**Comment by leouieda** [comment]
I've decided to ditch the website and use  the docs as the main page. The website was just a plain page with links  to the docs already, so it  makes more sense to have fatiando.org lead directly  to the docs.

So now  the docs push to fatiando.github.io. Older versions of the docs will be cloned to separate repos called "v0.1" etc.  This way, accessing the old site is just "fatiando.org/v0.1".

I also replaced the current theme with the [sphinx-bootstrap-theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme).

**Comment by leouieda** [comment]
The documentation now includes the main fatiando.org website. The site uses the [Sphinx bootstrap theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme) and is built and updated automatically by TravisCI when a pull request is merged to master.

The site is hosted on the [fatiando.github.io](https://github.com/fatiando/fatiando.github.io) repository. We still need to point fatiando.org to Github pages but the version on http://fatiando.github.io should work already.

The theme must be installed locally to build the site:

    pip install sphinx_bootstrap_theme

**Comment by leouieda** [comment]
@eusoubrasileiro since you've been working on docs for the wavefd ( #153 ) this might interest you. It shouldn't change anything for you right now. You'll just need to install the theme and the rest should work.

You should consider merging master into your development branch to get the latest changes.

**Comment by eusoubrasileiro** [comment]
@leouieda ok sire I will do that when I get my computer back hehe

**Pull request merged**
