### PR TITLE
Create a Use Cases page for papers and teaching

### PR DESCRIPTION
**Pull request by leouieda**
Adds a Use Cases page and what I could gather initially from citations
and mentions on google scholar. Includes links to PDFs and code whenever
I could find them online. Link to the new page from the docs and home
page.

### Checklist:

- [x] Make tests for new code (at least 80% coverage)
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Docstrings follow the style conventions
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `environment.yml`, `ci/requirements-conda.txt` and `ci/requirements-pip.txt`.
- [x] Documentation builds properly (run `cd doc; make` locally)
- [x] Changelog entry (leave for last to avoid conflicts)

### CODE REVIEW

**Comment by leouieda** [comment]
Heads up @fatiando/contributors. This PR will create a page to list publications and other things that have used Fatiando. I'd appreciate home help filling it in after the PR is merged. I included what I could gather initially but I'm sure I missed something. Conference presentations and other things are welcome as well.

**Comment by rafaelmds** [comment]
@leouieda I'm getting the fallowing error when trying to compile docs:

```
rm -rf cookbook
mkdir -p cookbook
mv _static/cookbook/*.rst cookbook

Build finished.

Building HTML files.

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.8

Extension error:
Could not import extension sphinx_gallery.gen_gallery (exception: No module named sphinx_gallery.gen_gallery)
Makefile:47: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by leouieda** [comment]
You need to install sphinx_gallery in order to build the docs. Run `pip install sphinx-gallery`

**Comment by rafaelmds** [comment]
@leouieda Thanks!
I forgot to active the fatiando-dev environment!

**Pull request merged**
