### PR TITLE
Stabilize derivatives in fatiando.gravmag

### LINKED ISSUE #194: Issues with gravmag fourier derivatives
I calculated derivative on some residual Bouguer anomaly data using gravmag fourier but they do not look right. 

There are edge effects in dz; moreover the horizontal derivatives dx and dy have a really weird striping.
A screen capture with comparison between the derivatives calculated in Fatiando and those calculated in Matlab is at this Dropbox location:
https://www.dropbox.com/s/l9z7lf8zq39p43f/Comparison.PNG?dl=0

This is my code, where data, X, and Y are matrices exported from Matlab:

    import numpy as np
    import scipy as sp
    from fatiando.gravmag import fourier

    # import gravity anomalies
    data = np.loadtxt('continued.txt')

    # import X and Y coordinate 2D arrays
    X = np.loadtxt('X.txt')
    Y = np.loadtxt('Y.txt')

    # convert data, X, and Y arrays to 1D
    data1D = data.ravel()
    X1D = X.ravel()
    Y1D = Y.ravel()

    # calculate derivatives using Fatiando a Terra and reshape output arrays back
    # to 2D
    xderiv = fourier.derivx(X1D, Y1D, data1D, data.shape)
    yderiv = fourier.derivy(X1D, Y1D, data1D, data.shape)
    zderiv = fourier.derivz(X1D, Y1D, data1D, data.shape)
    xderiv2D = np.reshape(xderiv, (81, 81))
    yderiv2D = np.reshape(yderiv, (81, 81))
    zderiv2D = np.reshape(zderiv, (81, 81))

### PR DESCRIPTION
**Pull request by leouieda**
As pointed out by @mycarta in #194, the FFT-based derivative calculations in `fatiando.gravmag` are unstable (see the figure below for a comparison with the MATLAB derivatives).

deriv

This PR tries to stabilize the derivatives by padding the input data and using different algorithms.

Fixes #194 and #167 

## Methods

The input data grids for FFT derivatives are padded using `numpy.pad` with the values in the borders of the grid. The padding is done to the nearest power of two. This solves the instabilities in the z derivative (specially in the edges). The horizontal derivatives are a bit better but still suffer from the "striping" seen above. 

Horizontal derivatives can be stabilized by using a central differences scheme instead of the FFT. This is what matlab uses to get the stable derivatives seen in the figure. The `derivx` and `derivy` functions will have options to use the finite differences instead of FFT.

## Checklist:

- [x] Make tests for new code
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in docs, requirements.txt, README, and .travis.yml
- [x] Documentation builds properly
- [x] All tests pass
- [x] Check cookbook recipes
- [x] Can be merged
- [x] Changelog entry (leave for last)
- [x] Firt-time contributor? Add yourself to `doc/contributors.rst` (leave for last)
- [x] Update I/O functions to read data with shape = (nx, ny)
- [x] Warn on the mailing list about the changes to `gridder.regular`

### CODE REVIEW

**Comment by leouieda** [comment]
I found an error in the way `fatiando.gridder.regular` works. In Fatiando, we assume that x is North-South and y is East-West. So if data is on a matrix, it would make sense that lines are x and columns are y. In the `gridder.regular` function we were assuming the opposite. The functions asked for a `shape = (ny, nx)`. The correct form should be `shape = (nx, ny)`.

This might impact some functions but it will be restricted mostly to the FFT derivatives so I'll make the fix in this branch.

**Comment by leouieda** [comment]
Things that are broken:

* Finite difference derivative
* Tests for `gravmag.sphere`. The "true" values were copied to doctests. Now they fail because the number are in a different order. I'll remove these tests for now and replace them with better tests later.

**Comment by leouieda** [comment]
@mycarta here are the update results for this branch:

## Old results


## New results
index

Generated using [this notebook](http://nbviewer.ipython.org/gist/leouieda/ac346557bd28f77861b8).

Notice that the x and y derivatives are exchanged. There is a lot of confusion regarding this because we use x -> North-South in Fatiando and that is not always the case with other software. It's good to check that the results have the proper orientation that you'd expect.

**Comment by mycarta** [comment]
Hi Leo Thanks for the follow-up on derivatives. Could you please take the
coordinates off from the images, and the notebook out altogether or use
mock coordinates?
Those coordinates are from my unpublished thesis and not supposed to be out
there, they were for your eyes only, my apologies I should have said it
clearly.

In my tutorial I'd be using mock coordinates.

Thanks

Matteo

**Comment by leouieda** [comment]
I'm so sorry about that! I should have noticed that your plots have no coordinates. It's fixed now. Also removed from the notebook (which doesn't include any data).

**Comment by mycarta** [comment]
If I'd mentioned it to begin with.....
All's well that ends well
:)
Thanks Leo

**Comment by eusoubrasileiro** [comment]
@leouieda awesome pictures of smootheness

**Pull request merged**
