### PR TITLE
Replace nosetests with py.test and move tests inside the package

### PR DESCRIPTION
**Pull request by leouieda**
Switched to [py.test](http://pytest.org/latest/) because `nose` is not developed anymore. Their own site [recommends using py.test](http://nose.readthedocs.io/en/latest/#note-to-users).

The tests are now part of the `fatiando` package and are installed with it in the `fatiando.tests` package. This means that we can run the tests on an installed version of the code, not just the one in the repository. Users can run `python -c "import fatiando; fatiando.test()"` after install to run our full test suite and make sure everything works.

For development, we'll have to use:

1. Install the code from your clone in [editable mode](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) using `pip install -e .`. You don't have to set `PYTHONPATH` anymore with this. Alternatively use `make develop`.
2. Edit the code, make new tests, etc
3. Run the tests using `py.test --doctest-modules --pyargs fatiando`. The `--pyargs` tells py.test to use the version installed (which is the code from repo because of 1. above). Alternatively use `make test`.
4. Check the test coverage with `py.test --doctest-modules --cov=fatiando --pyargs fatiando` or `make coverage`.

Extra things you'll need installed are `pytest` and `pytest-cov`, both available in Anaconda.

**Developers**: You'll need to update your branches after this gets merged. You should then move all new tests into `fatiando/tests`.

### Checklist:

- [x] Update instructions in Developer Guide
- [x] Tell users to run `python -c "import fatiando; fatiando.test()"` after install to test.
- [x] Make tests for new code (at least 80% coverage)
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Docstrings follow the style conventions
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `requirements.txt`, `environment.yml`, and `README.rst`
- [x] Documentation builds properly (run `make docs` locally)
- [x] Changelog entry (leave for last)

Notification for @fatiando/core-devs.

### CODE REVIEW

**Comment by eusoubrasileiro** [comment]
interesting... nose tests goood byee...

**Comment by leouieda** [comment]
@eusoubrasileiro :smile: there isn't much of a difference from what we use in Fatiando. But I took this opportunity to move the tests into the `fatiando` package, which I was meaning to do for quite some time. Also forced me to convert some bad doctests into proper tests.

**Comment by eusoubrasileiro** [comment]
I am your disciple! :+1: Nice

**Comment by leouieda** [comment]
@fatiando/core-devs I'm merging this now. Please update your branches to get the new test structure. Let me know if you need any help updating/merging.

**Pull request merged**
