### PR TITLE
Radial Average of Power Spectrum

### PR DESCRIPTION
**Pull request by santis19**
I've made a first try to implement the Radial Average of a Power Spectrum (or any real fft function) proposed in #224.

It needs a Power Spectrum in a square grid with odd number of points per axis in order to make sure that there is a grid point in the zero wave number.

The radial average is made by concentric rings using a grid of indexes in order to avoid troubles with frequencies. The rings have an inner radius equal to i - 1/2 and outer radius i+1/2, where i is an integer index ranging from 0 to half the grid's number of points per axis. The first ring (i=0) is a circle containing only the zero frecuency point. The next is a ring surrounding this circle, and so on.

rings

Also, it calculates the standard deviation for each average, and the 1D wave numbers array.

Here I leave an example:
```
import numpy as np
import matplotlib.pyplot as plt
from fatiando.datasets import fetch_bouguer_alps_egm
from fatiando.gridder import load_surfer
from fatiando.gravmag import transform
    
# Load Bouguer Anomaly Data
fetch_bouguer_alps_egm(fname="alps-bouguer.grd")
x, y, bg, shape = load_surfer("alps-bouguer.grd")

## Puts Data in 2d array grid
y = y.reshape(shape) ## Easting
x = x.reshape(shape) ## Northing
bg = bg.reshape(shape)

## Cut the data to a square grid
x, y, bg = x[0:181, 19:200], y[0:181, 19:200], bg[0:181, 19:200]
dx = abs(x[1, 0] - x[0, 0])

## Calculates the Power Spectrum and wave numbers
kx = 2*np.pi*np.fft.fftfreq(181, dx)
ky, kx = np.meshgrid(kx, kx)
fft_bg = np.fft.fft2(bg)
log_power_spectrum = np.log(abs(fft_bg)**2)

## Calculates the Radial Average
k, average, rms = transform.radial_average(log_power_spectrum, dx)

## PLOTS
plt.axes(aspect='equal')
plt.contourf(y, x, bg, 150)
plt.colorbar(label='mGal')
plt.title("Bouguer Anomaly")
plt.xlabel("m")
plt.ylabel("m")
plt.show()

kx = np.fft.fftshift(kx)
ky = np.fft.fftshift(ky)
log_power_spectrum = np.fft.fftshift(log_power_spectrum)
plt.axes(aspect='equal')
plt.contourf(ky, kx, log_power_spectrum, 150)
plt.colorbar()
plt.title("Log Power Spectrum")
plt.show()

plt.errorbar(k, average, yerr=rms, fmt='.')
plt.show()
```

ejemplo

### CODE REVIEW

**Comment by leouieda** [comment]
Hi @santis19 thanks for giving this a try.

I'm a bit busy right now but I'll have a more detailed look at your code as soon as I can. One thing that caught my eye now is that you're assuming that the grid spacing is equal in both directions. This is a bit implicit in the fact that you map the spectrum index to frequencies. This will not always be the case and would give wrong results if it isn't. 

The restrictions of a square grid and even number of points seem a bit too much. I understand why you make them but there must be a way to calculate the spectrum without such restrictions. I think I have some code for that somewhere lost in my hard-drive. I'll see if I can find it. There might be some insight into how you could do that.

It would also be good if the spectrum calculation was inside the function so that you could give it the raw data and get the spectrum. That would make the functions easier to use and such computations are generally cheap anyway. That is not urgent for now but just to have this in mind.

Could you include the code you posted here as a cookbook recipe?

Either way, this is already a great start! Thanks!

**Comment by santis19** [comment]
Hi Leo,

You're right about the big restrictions (square grid and odd number of
points), that may be easy to solve: take the first ring as the first circle
containing the first 4 points (in case of even number of points), and for a
non-square grid just cutting it to make it square.

About the equal spacing, you're right, the better way to generalize this
function would be to just work with wave numbers instead of indexes, taking
them as an input for the function.

On the other hand I don't agree about calculating the power spectrum from
raw spatial data. I think that would be better to have functions in space
domain and functions for frequencies domain. For example, supose I want to
get the radial average of a filtered data. In that case one would have to
calcuate the fft of the raw data, filter it, inverse it to spatial and then
calculate the spectral average what implies calculates the fft once again.
For small grids that's no problem, but when you are working with big ones
(or padded grids) it would be not very efficient.

I'll agree this example to the cookbook right away!

Thanks!

2015-08-13 11:47 GMT-03:00 Leonardo Uieda <notifications@github.com>:

**Comment by leouieda** [comment]
> You're right about the big restrictions (square grid and odd number of points), that may be easy to solve: take the first ring as the first circle containing the first 4 points (in case of even number of points), and for a non-square grid just cutting it to make it square. 

> About the equal spacing, you're right, the better way to generalize this function would be to just work with wave numbers instead of indexes, taking them as an input for the function. 

A way to do both of these would be:
1. use the frequencies instead of indexes
2. calculate the radial "distance" of each spectrum grid point from the 0 frequency origin (can use `numpy.hypot` for this)
3. group the grid points by "distance" ranges. The number of ranges could be an input of the function.
4. take the mean of each group

> On the other hand I don't agree about calculating the power spectrum from raw spatial data. I think that would be better to have functions in space domain and functions for frequencies domain. For example, supose I want to get the radial average of a filtered data. In that case one would have to calcuate the fft of the raw data, filter it, inverse it to spatial and then calculate the spectral average what implies calculates the fft once again. For small grids that's no problem, but when you are working with big ones (or padded grids) it would be not very efficient.

That's a good point. If we ask for the spectrum (and should ask for the frequencies as well then) we should provide a better function to calculate that from the data. It should use the `_fftfreqs` functions to get the frequencies.

**Comment by drandykass** [comment]
Did you wind up resolving this (I just joined the mailing list and github)?  Traditionally, the easiest way to do this would be to create something like a numpy meshgrid of wavenumbers in the x and y directions corresponding to the power spectrum, then using those to create a 3rd meshgrid of radial wavenumbers.  Then it's a simple matter of vectorizing the power spectrum and radial wavenumber, sorting them, and averaging the duplicates.  The trick is how to subsequently smooth that result--moving average filters and such will alter the area under the curve.  My usual method is to finely interpolate the 1D vectors to a fine grid, then use a trapezoidal rule to compute the final, smoothed points.  This works with non-square and grids with x and y sampled differently.

**Comment by drandykass** [comment]
Oh, and I really really like the standard deviation calculations.  That's a nice touch I hadn't thought of before.

**Comment by leouieda** [comment]
@drandykass I haven't heard back from @santis19 in a while. To be fair, I have been neglecting Fatiando for last few months.

The  discussion around taking space-domain or frequency-domain input and output ties in with #225. I'll create a separate issue to discuss this.

@drandykass if @santis19 is unable to finish this, would you like to take a stab at finishing? You can pull in the commits @santis19 already made, that way he gets credit for his contribution as well. 

@santis19 if you plan on continuing this in the future, there is no hurry from my part.

**Comment by drandykass** [comment]
Sure, if @santis19 can't for whatever reason.  I'll stand by on that one
though.

On Wed, Nov 25, 2015 at 1:58 PM, Leonardo Uieda <notifications@github.com>
wrote:

> @drandykass <https://github.com/drandykass> I haven't heard back from
> @santis19 <https://github.com/santis19> in a while. To be fair, I have
> been neglecting Fatiando for last few months.
>
> The discussion around taking space-domain or frequency-domain input and
> output ties in with #225 <https://github.com/fatiando/fatiando/issues/225>.
> I'll create a separate issue to discuss this.
>
> @drandykass <https://github.com/drandykass> if @santis19
> <https://github.com/santis19> is unable to finish this, would you like to
> take a stab at finishing? You can pull in the commits @santis19
> <https://github.com/santis19> already made, that way he gets credit for
> his contribution as well.
>
> @santis19 <https://github.com/santis19> if you plan on continuing this in
> the future, there is no hurry from my part.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatiando/fatiando/pull/230#issuecomment-159730118>.
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by leouieda** [comment]
I'm closing this Pull Request because it's been inactive for a long time. The branch is probably very out of sync with `master`.

If you want to continue working of this, please [sync your fork](https://help.github.com/articles/syncing-a-fork/), update your branch, and re-submit the PR.  Let me know if you need any help doing this!

Sorry for the hassle! This is not a critique of your work, just a way to keep things fresh in the project. I hope you'll consider re-submitting.

**This is a message template.**

**Pull request closed without merging**
