### PR TITLE
Merge gravmag.fourier with gravmag.transform

### PR DESCRIPTION
**Pull request by mtb-za**
This closes issues #171 and #154.

Updated the two recipes that I know use the gravmag.fourier.* modules as
well. This was suggested as #171.

The *.ansig function was also replaced with *thd, as part of #154.

This changeset is **not** backwards compatible, because it moves functions to different modules.

**Update (@leouieda 26-03-2015)**: Added the [PR checklist](http://fatiando.github.io/develop.html#pull-requests) to track the tasks that need to be done.

## Checklist:

- [x] Make tests for new code
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in docs, requirements.txt, README, and .travis.yml
- [x] Documentation builds properly
- [x] All tests pass
- [x] Can be merged
- [x] Changelog entry
- [x] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last)

### CODE REVIEW

**Comment by leouieda** [comment]
@mtb-za I've updated the PR description with a checklist that we've been using on PRs.

I had a look at the [TravisCI report](https://travis-ci.org/fatiando/fatiando/builds/55913471) for this commit and there a lot of things breaking in the tests. I expected this much because the `fourier` module was imported on other places. Now all of thoses modules will give `ImportError`. See the test output here: https://travis-ci.org/fatiando/fatiando/builds/55913471#L757

You can run the tests on your machine using `make test`. You'll need to install the `nose` and `pep8` packages if you don't have them:

    conda install nose
    pip install pep8==1.6.0

**Comment by mtb-za** [comment]
Weird. I am getting an error in `tesseroid.py`.

Not sure why it is giving this error, I thought it was expected that numba and pure python do the same?

In any case, not seeing any errors related to `fourier` any more.

>ERROR: gravmag.tesseroid numba and pure python implementations give same result
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
>  File "/home/mtb/bin/os_geo_stuff/fatiando/test/test_gravmag_tesseroid.py", line 89, in test_numba_vs_python
>    nb = func(lon, lat, height, model, engine='numba')
>  File "/home/mtb/bin/os_geo_stuff/fatiando/fatiando/gravmag/tesseroid.py", line 383, in potential
    ratio=ratio, engine=engine, njobs=njobs, pool=pool)
>  File "/home/mtb/bin/os_geo_stuff/fatiando/fatiando/gravmag/tesseroid.py", line 277, in _dispatcher
    field])
>  File "/home/mtb/bin/os_geo_stuff/fatiando/fatiando/gravmag/tesseroid.py", line 301, in _forward_model
    module = _get_engine(engine)
>  File "/home/mtb/bin/os_geo_stuff/fatiando/fatiando/gravmag/tesseroid.py", line 224, in _get_engine
    module = _tesseroid_numba
>NameError: global name '_tesseroid_numba' is not defined

**Comment by leouieda** [comment]
@mtb-za sorry, I just looked at this properly now. It seems that you don't have numba installed. The new tesseroid code need numba==0.17 (install with `conda install numba`). I believe that's probably why your test failed and why it was so slow. When numba is missing the code falls back to a numpy implementation (which is **really** slow).

**Comment by mtb-za** [comment]
Ah right. Will get onto that. Need to figure out getting llvm onto this machine (since I am not using conda here). Hopefully I can clear it up over the weekend. But I think that I have managed to clear most of the issues up, so will push soon and let Travis check.

I am also getting PEP8 compliance warnings, but not sure where.

**Comment by leouieda** [comment]
OK, I don't know how hard it will be to get numba without Anaconda. I think you can install the conda package manager on your system python and use the packages provided by Continuum. Not sure. If you can't manage it, you should try asking them for help. They are usually very nice people and eager to help (one of them helped me a lot with the numba code).

To see the specific PEP8 errors, run `make pep8`.

**Comment by leouieda** [comment]
Also, you can push as often as you want. Travis CI won't mind the extra work (and it's free). Plus, this way your changes are backup.

**Comment by leouieda** [comment]
@mtb-za finally got a chance to look at this properly. Great stuff! Seems like you're almost done.

One thing I noticed is that you named the function `thd`. Is that Total Horizontal Derivative? If so, a more accurate name would be Total Derivative or Total Gradient Amplitude (the latter is more used). The thd would not include the z derivative, right? It would be nice to have both actually.

**Comment by leouieda** [comment]
Could you please rename the cookbook recipe to gravmag_transform_thd.py (or the other name the function will receive)?

**Comment by leouieda** [comment]
More on that, any recipe or file with `fourier` in the name will need to renamed. You can do this with `git mv `.

Could you check if all gravmag recipes run? 

This is why I try to avoid renaming as much as possible. It is a lot of bookkeeping work and not that fun to do. 

Thanks a lot for putting in the effort!

**Comment by mtb-za** [comment]
I seem to recall testing the recipes manually, but I will re-run them all and make sure that nothing obvious is wrong.

I went with what was suggested in #154 in terms of naming. So `ansig` became `thd`. Slightly confused now, but I can change it to whatever you want. Does `total_gradient_amplitude` work or would you prefer something shorter, like `tga`?

And it is a pleasure to help out. This was a good first contribution, I think. I am certainly much more up to speed with how you guys are doing the development, so I feel more confident that I can bring more to the project (which will benefit my own).

**Comment by leouieda** [comment]
> I seem to recall testing the recipes manually, but I will re-run them all and make sure that nothing obvious is wrong.

Perfect!

> I went with what was suggested in #154 in terms of naming. So ansig became thd. Slightly confused now, but I can change it to whatever you want. Does total_gradient_amplitude work or would you prefer something shorter, like tga?

Sorry about that, it was my mistake. I got things confused in the issue. The correct name would be total gradient amplitude, so I guess `tga` is a good name for the function. 

> And it is a pleasure to help out. This was a good first contribution, I think. I am certainly much more up to speed with how you guys are doing the development, so I feel more confident that I can bring more to the project (which will benefit my own).

That's great to know! This was a nice one to get started because it involves many different places in the code. 

Also, I edited the main description of the PR with an extra item on the checklist.

**Comment by mtb-za** [comment]
The cookbook recipes all seem to be ok, despite getting a number of errors similar to this:

>/usr/lib/python2.7/site-packages/matplotlib/text.py:52: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if rotation in ('horizontal', None):
>/usr/lib/python2.7/site-packages/matplotlib/text.py:54: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif rotation == 'vertical'

That particular example is from `gravmag_harvester_grav.py`, but is not the only one for which I am getting these warnings. I do not think that this is something I have done, but it may be something about my setup.

**Comment by leouieda** [comment]
@mtb-za that is from matplotlib. I think it comes from the `pyplot.colobar` function and is probably  causes by some Python 3 compatibility (py3k changed the handling of strings and unicode).

OK, looking good! From the checklist it seems that you need to check that the docs build properly and add yourself to our contributor list in the `doc` folder. Let me know if you need any help with any of that.

**Comment by mtb-za** [comment]
Cool. Cookbook seems to checkout. Those filenames are changed. So where can I check the docs?

**Comment by leouieda** [comment]
You'll need to do this locally. See http://fatiando.github.io/develop.html#documentation for instructions. Just do a quick visual inspection on the modules you have changed and see if things look OK.

**Comment by mtb-za** [comment]
Hi @leouieda 
So I have built the docs, and they look good, apart from still showing `*.fourier` in `api/gravmag.html`. This is strange because `*.fourier` has been removed entirely. There is no file for it to import from.

Any idea what I may have missed here? Otherwise, this is pretty much complete, I think. Just need to check the changelog against a more recent one, and update the contributors list.

**Comment by leouieda** [comment]
You'll have to remove the reference for it from `fatiando/gravmag/__init__.py`.

Have you pushed all your latest commits? The PR hasn't been updated in a while. You can push to this branch as often as you like.

By the way, did you rename the tdh function?

You might have merge conflicts because of the changelog if any other PR was merged. That's why I added the "leave for last" to the checklist. Let me know if you need help resolving the conflicts.

**Comment by mtb-za** [comment]
Cool, have done that, the docs look ok now. I *think* that that is pretty much everything now.

Have pushed, if it passes the travis build, I will update the changelog and contributor lists and make a final push.

**Comment by mtb-za** [comment]
Thanks Leo. I knew I was missing something obvious for that.

**Comment by leouieda** [comment]
@mtb-za everything looks good to me. Are there any other commits that you want to push? If not, I think this is ready to merge.

**Comment by mtb-za** [comment]
Nothing from my side, no.

**Comment by leouieda** [comment]
@mtb-za merged! Congratulations and welcome to the team!

**Pull request merged**
