### PR TITLE
Refactor fatiando.inversion to use abstract base classes and smarter caching

### PR DESCRIPTION
**Pull request by leouieda**
Refactoring the entire `fatiando.inversion` package.

* Using `ABCMeta` and abstract methods for `Misfit`
* A smarter cache system that uses classes to sort of decorate methods whose results you want to keep cached. This can be expanded to cache matrices to HDF5 files later on.
* Get rid of `Objective`. It is just adding needless hierarchy. The operator overloading will be a mix-in class.
* Summing makes a `MultiObjective` object. This class will allows indexing to get at the individual members. So you can do `solver = Misfit(...) + 10*Damping(...); solver[0].predicted()`.
* Easier and more intuitive subclassing. Thanks to the smarter cache system and `MultiObjective`, we no longer use `_get_predicted` and `_get_jacobian`. Now you implement `predicted(p)` and `jacobian(p)`.
* `estimate_` is a property. It uses a new method called `fmt_estimate` that transforms `p_` into something more useful.
* No longer need to overload `fit` because of the above. Now you just implement `fmt_estimate` to do what you want. 
* Get rid of the `subset` method and the need for `positional` and `model` attributes. Just use normal class attributes instead. The more complicated form was only needed to implement `subset` in a general way. But that is not very useful as splitting a dataset is highly dependent on what that dataset is. This will be left to individual solvers to implement. Reduces the complexity of `Misfit` a lot.
* `Misfit` is no longer divided by the number of data. I always forgot about this and it was causing problems. The same effect can easily be achieved using the multiplication operation.
* Establish an API for the `inversion` package so that we can import all public facing classes with `from fatiando.inversion import LCurve, Damping, ...` instead of getting a single class from every module. This will allow us to use as many modules as we want in the package.

## TODO

- [x] Import public classes into `fatiando.inversion` to make them accessible.
- [x] Move `Misfit` to its own module.
- [x] Move `LCurve` to its own module.
- [x] Better way to implement `subset` method. Maybe get rid of it. (Got rid of it)
- [x] Adapt regularizing functions
- [x] Adapt LCurve
- [x] Convert inverse problems to new API
- [x] Add option to capture and return run statistics from the solvers. This will be stored in the solver classes to print on demand.
- [x] Create/update cookbook recipes (remove LCurve from most, make separate recipe)
- [x] Replace `six` by `future`

### Docstrings that need update

- [x] base
- [x] regularization
- [x] hyper_param
- [x] misfit
- [x] optimization
- [x] __init__

### Inversions to convert

- [x] seismic.srtomo
- [x] gravmag.eqlayer
- [x] gravmag.euler
- [x] seismic.profile
- [x] seismic.epic2d
- [x] geothermal.climsig
- [x] gravmag.basin2d
- [x] gravmag.magdir

## Checklist:

- [x] Make tests for new code
- [x] Create/update docstrings
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in docs, requirements.txt, README (deps: `future`)
- [x] Documentation builds properly
- [x] All tests pass
- [x] Can be merged
- [x] Changelog entry (warn about future as dependency)

### CODE REVIEW

**Comment by leouieda** [comment]
- [ ] Finish fixing eqlayer recipes

**Comment by leouieda** [comment]
Euler solutions for the expanding window are strange. They are falling outside the bodies in the recipe.

**Comment by leouieda** [comment]
Solved expanding window problem by dividing the Hessian by ndata before calculating the uncertainty.

**Comment by leouieda** [comment]
Should exchange `six` for [future](http://python-future.org/). It's a more mature package and seems to offer better support for trading `xrange` for `range` and the Python 3 way of creating custom iterators (the `__next__` method).

**Comment by leouieda** [comment]
@fatiando/contributors just to let everyone know that I've finally merged this PR to master. It changes the `fatiando.inversion` package completely. You can view the changes in the PR description. The package  docs have been updated and can be seen on the development version of the site: http://www.fatiando.org/dev/api/inversion.html

If anyone has any suggestions/comments, they are more than welcome. You can do that here or open a new issue (in case it's a bug or proposal for changes).

**Comment by drandykass** [comment]
FYI, this broke all the inversion unit tests for me--I pulled the upstream
master in.  I was missing the module 'future.builtins'.  I did pip install
of future and all was good.  Might need to add that to the install doc
until everyone is over into Python 3.

Also, that old comparison error is back, where there is an extra space in
the array (line 319 in fatiando.inversion).

On Fri, Dec 11, 2015 at 8:02 AM, Leonardo Uieda <notifications@github.com>
wrote:

> @fatiando/contributors
> <https://github.com/orgs/fatiando/teams/contributors> just to let
> everyone know that I've finally merged this PR to master. It changes the
> fatiando.inversion package completely. You can view the changes in the PR
> description. The package docs have been updated and can be seen on the
> development version of the site:
> http://www.fatiando.org/dev/api/inversion.html
>
> If anyone has any suggestions/comments, they are more than welcome. You
> can do that here or open a new issue (in case it's a bug or proposal for
> changes).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatiando/fatiando/pull/127#issuecomment-163957703>.
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by drandykass** [comment]
Oh, you know what?  If I had read the changelog, I would have seen that you
were completely aware of the issue in the first paragraph.  Please
disregard.

On Mon, Dec 14, 2015 at 9:38 AM, M. Andy Kass <kass.andrew@gmail.com> wrote:

> FYI, this broke all the inversion unit tests for me--I pulled the upstream
> master in.  I was missing the module 'future.builtins'.  I did pip install
> of future and all was good.  Might need to add that to the install doc
> until everyone is over into Python 3.
>
> Also, that old comparison error is back, where there is an extra space in
> the array (line 319 in fatiando.inversion).
>
> On Fri, Dec 11, 2015 at 8:02 AM, Leonardo Uieda <notifications@github.com>
> wrote:
>
>> @fatiando/contributors
>> <https://github.com/orgs/fatiando/teams/contributors> just to let
>> everyone know that I've finally merged this PR to master. It changes the
>> fatiando.inversion package completely. You can view the changes in the
>> PR description. The package docs have been updated and can be seen on the
>> development version of the site:
>> http://www.fatiando.org/dev/api/inversion.html
>>
>> If anyone has any suggestions/comments, they are more than welcome. You
>> can do that here or open a new issue (in case it's a bug or proposal for
>> changes).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fatiando/fatiando/pull/127#issuecomment-163957703>.
>>
>
>
>
> --
>
> ------------------------------------------------------------------------------------
> Dum inter homines sumus, colamus humanitatem.
>
> ------------------------------------------------------------------------------------
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by leouieda** [comment]
:laughing: no problem! It's always tricky  adding new dependencies but this one would have been necessary for Python 3 support eventually.

**Pull request merged**
