### PR TITLE
Correction to 'gridder.cut' function

### PR DESCRIPTION
**Pull request by santis19**
With this correction we can give any pair of opposite vertices of the area to cut, instead of giving the bottom-left vertex first and the upper-right in second place, as before.

## Checklist:

- [ ] Make tests for new code
- [ ] Create/update docstrings
- [ ] Include relevant equations and citations in docstrings
- [x] Code follows PEP8 style conventions
- [ ] Code and docs have been spellchecked
- [ ] Include new dependencies in docs, requirements.txt, README, and .travis.yml
- [ ] Documentation builds properly
- [ ] All tests pass
- [ ] Can be merged
- [ ] Changelog entry (leave for last)
- [ ] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last)

### CODE REVIEW

**Comment by leouieda** [comment]
@santis19 thank you for this fix! This code is quite old (~4 years) and I didn't do nearly as much defensive programming back then. It is really helpful to have more eyes looking at the code.

I like that you caught a potential sources of bugs. I think it would be better to raise an error and warn the user that the input was wrong. If we silently fix the input, this could hide a bug the code calling this function. It is better to fail fast and often.

A way to this is using the `assert ` statement. See some of the code in the `gravmag.tesseroid` module for an example of using `assert` to check function input.

It would also be nice to have a unit test that checks if the code really raises the error when it should. Have a look at the `test/test_gravmag_tesseroid.py`   file for an example of testing `asserts `. I can give you a have with that later if you'd like.

**Comment by santis19** [comment]
Thank you for your response Leo!

If you think that raising an error is better I'd do it, but in this case I think that is better to fix the input because the old situation is included in the new one. What I mean is that if any code intentionally calls this function putting the lower left vertix first and then the upper right, it will continue working as it is.

But, in every day work when we call this function we care about cutting an area, without concerning about the order of the vertices of the rectangle. So that's why I think that it's better to fix the input than raising an error.

Greetings!

**Comment by leouieda** [comment]
@santis19 I thought a lot about this. I agree that being flexible with the inputs can be nice when you're using the function to run a script. However, this functions is used in the internals of some `gravmag` modules (all that have to do with windowing procedures, like Euler deconvolution). So allowing wrong input in `gridder.cut` can hide bugs in things like `fatiando.gravmag.euler`. And these bugs will be hard to find.

I still think that the best thing to do is to fail with an error for wrong input. If you're writing a script and get this error, than you know right away and can easily fix it.

**Comment by santis19** [comment]
Yes, I think you're right Leo!

**Comment by leouieda** [comment]
I'm closing this Pull Request because it's been inactive for a long time. The branch is probably very out of sync with `master`.

If you want to continue working of this, please [sync your fork](https://help.github.com/articles/syncing-a-fork/), update your branch, and re-submit the PR.  Let me know if you need any help doing this!

Sorry for the hassle! This is not a critique of your work, just a way to keep things fresh in the project. I hope you'll consider re-submitting.

**This is a message template.**

**Pull request closed without merging**
