### PR TITLE
Make the z variable an 1d-array

### PR DESCRIPTION
**Pull request by birocoles**
Fixes [#279](https://github.com/fatiando/fatiando/issues/279)

Modifies the mesher.PointGrid to accept variable depths (z coordinate). Such 
improvement will make possible to use undulating equivalent layers in 
gravmag.eqlayer.

### Checklist:

- [x] Make tests for new code (at least 80% coverage)
- [x] Create/update docstrings
- [x] Include relevant equations and citations in docstrings
- [x] Docstrings follow the style conventions
- [x] Code follows PEP8 style conventions
- [x] Code and docs have been spellchecked
- [x] Include new dependencies in `doc/install.rst`, `requirements.txt`, `environment.yml`, and `README.rst`
- [x] Documentation builds properly (run `make docs` locally)
- [x] Changelog entry (leave for last)
- [x] First-time contributor? Add yourself to `doc/contributors.rst` (leave for last)

Notification for @fatiando/core-devs

### CODE REVIEW

**Comment by leouieda** [comment]
@birocoles great! I'll look into this later on. Let me know when you're done or if you need help with anything.

**Comment by birocoles** [comment]
@leouieda , all tests I have done passed. What I have to do now?

**Comment by leouieda** [comment]
@birocoles I update the branch to the latest master. The tests have moved to inside the package (`fatiando/tests`) so I moved your test file there. One of the new eqlayer tests started failing so I fixed that too. I just need to check the test coverage and documentation build now.

**Comment by leouieda** [comment]
@birocoles looking at the [test coverage](https://github.com/fatiando/fatiando/blob/master/Makefile#L31), I noticed that there were a few lines of `PointGrid` that weren't covered by the tests. They were mainly the lines that check for invalid input and raise an exception. I implemented some tests for these cases and also added tests for the basic functionality of the class. These used to be only in the doctest but it's better to have them in the unit tests as well to make things more explicit.

The tests also serve the purpose of documenting how the class works, so testing the basic usage is a good thing.

**Comment by leouieda** [comment]
When the tests finish running, all that is left is adding an entry in the changelog. After that, we're done!

**Comment by leouieda** [comment]
@birocoles Merged!

**Comment by birocoles** [comment]
@leouieda great!

**Pull request merged**
