### PR TITLE
Software Carpentry broken link fix in developer guide

### LINKED ISSUE #240: Dev Page - Broken link to testing
Software Caprentry has removed their lessons on testing for a bizarre reason.  As a consequence, the link provided under the Testing section on the dev pages is now broken (despite it STILL being the top google result if you search 'testing' on the software-carpentry site).

More information:
http://software-carpentry.org/blog/2014/10/why-we-dont-teach-testing.html

I do not have an alternative suggestion for a tutorial on building tests yet, though I will be searching; I need to build tests for new code now.

### PR DESCRIPTION
**Pull request by drandykass**
Generalised all the software-carpentry links in the developers guide.  Fixes #240

### CODE REVIEW

**Comment by drandykass** [comment]
I created a new branch (sc-devfix) for just fixing the broken links in the developers guide, but it's showing all my commits for pad_arrays.  Did I accidentally branch a branch?  Can you do that?

**Comment by leouieda** [comment]
@drandykass well, there is probably a way do it without deleting the branch and staring over. Though knowing git I don't think it will be easy.

Probably better to make a new branch from `master`, copy over the file from this branch, and make a new commit. 

You'll want to pull in the changes from the master of `fatiando/fatiando`. You can do this by:

1. Adding the `fatiando/fatiando` repo as a remote (if you haven't already):

        git remote add upstream https://github.com/fatiando/fatiando.git

2. Pull in the commits from upstream master to your branch:

        git checkout MY_BRANCH
        git pull upstream master

**Comment by leouieda** [comment]
Also, don't worry about this sort of thing. It happens all the time. Sadly, even after years using git :disappointed:

**Comment by drandykass** [comment]
https://xkcd.com/1597/

Why would I add the fatiando/fatiando repo rather than continuing to use my
fork?  What's the theory there?



On Thu, Dec 3, 2015 at 2:52 PM, Leonardo Uieda <notifications@github.com>
wrote:

> Also, don't worry about this sort of thing. It happens all the time.
> Sadly, even after years using git [image: :disappointed:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatiando/fatiando/pull/244#issuecomment-161796442>.
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by leouieda** [comment]
>https://xkcd.com/1597/

Hahaha that pretty much sums it up. I use that comic in the git part of my class.

>Why would I add the fatiando/fatiando repo rather than continuing to use my fork? What's the theory there?

Well, your fork is a separate repository from `fatiando/fatiando` (I'll call this upstream). So your master branch is not the same the master of upstream. Since I merged #242 today there will be commits in upstream master that you don't have in your fork. When you create a branch from your master, it will be behind upstream master by a few commits. This wouldn't be a problem except that the PR changes the `doc/changelog.rst` file, which you'll change as well. So this would create a conflict.

The way around this is to always update your branches with the latest from upstream master. The commands above don't replace your fork with `fatiando/fatiando`, it  juts adds another option to pull commits from. Your fork is still the "origin" remote. Yeah, it gets kind of confusing with all the jargon.

For example, you can fetch the latest commits from upstream to your clone, then push them to your forks master branch like so:

    git checkout master
    git pull upstream master
    git push origin master

**Comment by drandykass** [comment]
OK, this pull request can be deleted.  PR 245 supersedes this pull request, and should have been done properly, as per @leouieda instructions.

**Pull request closed without merging**
